/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team2084_CMonster2016_vision_BoulderProcessor */

#ifndef _Included_org_usfirst_frc_team2084_CMonster2016_vision_BoulderProcessor
#define _Included_org_usfirst_frc_team2084_CMonster2016_vision_BoulderProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_usfirst_frc_team2084_CMonster2016_vision_BoulderProcessor
 * Method:    processNative
 * Signature: (JJDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_usfirst_frc_team2084_CMonster2016_vision_BoulderProcessor_processNative
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
