/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor */

#ifndef _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
#define _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
 * Method:    processNative
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_processNative
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
