/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor */

#ifndef _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
#define _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_ESTIMATED_CAMERA_LATENCY
#define org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_ESTIMATED_CAMERA_LATENCY 0.1279
#undef org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_GYRO_UPDATE_RATE
#define org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_GYRO_UPDATE_RATE 60L
/*
 * Class:     org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor
 * Method:    processNative
 * Signature: (JJJIDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_processNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
