/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_ProcessingThread */

#ifndef _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_ProcessingThread
#define _Included_org_usfirst_frc_team2084_CMonster2016_vision_HighGoalProcessor_ProcessingThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
